# 1 - Primeros pasos en Google Colab. Almacenamiento en Google Drive

Vamos a usar Google Drive como fuente de datos.
El siguiente código importa las librerías necesarias para poder usar ficheros en Google Drive, esto es **PyDrive**

Además de llamar a la librería de **Pandas** para manejar ficheros csv. 

Al ejecutar el siguiente código os pedirá permiso para que *Google Cola*b pueda acceder a Drive ( **echádle un vistazo a los permisos** ) y a continuación os pedirá una cuenta de Drive, lo mejor es  usar la corporativa que os han dado el centro.

Antes de ejecutar el código subid un fichero csv a Drive, llamadlo **ejemplo.csv** con el siguiente contenido


---

* Experience, Salary
* 1.2,3434.00
* 3.1,7263.50
* 2,2121.00
* 1.1,1200.00
* 3.3,3129.40
* 10,1000.00
* 32,7893.00
* 4,9939.00
* 3,4343.00
* 56,3434.00
* 6,343.00
* 8,32.00
* 9,3444,00


---

**nota:** el fihero csv va sin los puntos, los hemos puesto por motivos de visualización

Una vez en Drive, botón derecho sobre el fichero *ejemplo.csv* y vamos a **obtener enlace**, en el cuadro que se abre ( *repasa los permisos* ), pichamos en el botón de abajo a la izquierda **copiar enlace**. Guarda ese enlace que se usará después.

In [ ]:
# Code to read csv file into Colaboratory:

# instalamos la libreria de acceso a Drive

!pip install -U -q PyDrive

# importamos pandas para manipular csv

import pandas as pd

# importamos la libreria para manipular cadenas y usar 
# expresiones regulares

import re 

# importamos librerías de acceso a Drive

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# Authenticate and create the PyDrive client.

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

copia el enlace al fichero csv en la variable link. Extraemos el id del fichero usando la librería de Python para expresiones regulares.

In [ ]:
link = "https://drive.google.com/file/d/1EdfQ42me8sP3G3JdPMd8uTIMYH5Qapv9/view?usp=sharing"

# usamos la libreria re de Python para buscar y extraer subcadenas. En big data es una herramienta fundamental.

# paso 1, definimos el regex a usar

p = re.compile(r".*\/d\/(\w+)\/view.+")

# paso 2, aplicamos el regex sobre la cadena de la variable link

resultado =  p.search(link)

#paso 3, con la subcadena extraida de la variable link definimos variable id 
#y la mostramos por pantalla para comprobar que se ha extraído correctamente.

id = resultado.group(1)
print(resultado.group(1))

1EdfQ42me8sP3G3JdPMd8uTIMYH5Qapv9

una vez tenemos el id, usamos la libreria de python para llamar a ese fichero y se lo pasamos a read_csv que lo carga en la variable df3.

In [ ]:
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('ejemplo.csv')  
df3 = pd.read_csv('ejemplo.csv')
# Los datos están ahora almacenados en un Pandas Dataframe
# el método head muestra los 4 ó 5 primeros elementos del csv, lo dejamos comentado
#df3.head()
# muestra todo el contenido del fichero.
df3

    Experience   Salary
0          1.2  3434.00
1          3.1  7263.50
2          2.0  2121.00
3          1.1  1200.00
4          3.3  3129.40
5         10.0  1000.00
6         32.0  7893.00
7          4.0  9939.00
8          3.0  4343.00
9         56.0  3434.00
10         6.0   343.00
11         8.0    32.00
12         9.0  3444.00
13        12.0  1200.00
14        21.0  4500.23
15         8.9   200.33